### ISSUE TITLE
Site idea

### ISSUE THREAD

**Issue by bclinkinbeard** [idyll-lang/editor-playground#1]
I don't know if this goes here or in the docs-redux repo, but I keep picturing something and wanted to write it down.

I think the editor is compelling enough that it should be front and center. I think a great homepage would be the logo, a headline, a couple sentences of description, and then the editor inline. Controls along the top of the editor could allow you to switch between pre-made examples (that you could of course edit) or start from scratch. We could also implement live layout and theme switching like I did in Literasee.

If we did those things and ported the existing examples to work inside it I think we'd have a hell of a site. People could understand the project in 20 seconds.

**Comment by mathisonian** [comment]
I'm going to move this to docs-redux

**Comment by mathisonian** [comment]
Moved to https://github.com/idyll-lang/docs-redux/issues/3
